### ISSUE TITLE
Create Statistic component

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#10]
Here is the original one: https://semantic-ui.com/views/statistic.html.

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by DKunin** [comment]
Will take a look at this!

**Comment by mariolamacchia** [comment]
Released in 0.0.18
