### ISSUE TITLE
Move docs to nuxt-generate

### ISSUE THREAD

**Issue by ArStah** [Semantic-UI-Vue/Semantic-UI-Vue#106]
Hi @mariolamacchia, do you mind if i'll make your docs as nuxt generate project?

**Comment by mariolamacchia** [comment]
Do you mean to generate a static project from the docs?

**Comment by ArStah** [comment]
Yes, it will resolve #81. And i just want to do something on nuxt generate, so it's better to do something helpful)

**Comment by mariolamacchia** [comment]
It would be awesome 😄
