### ISSUE TITLE
Label with child elements

### ISSUE THREAD

**Issue by JasonTrue** [Semantic-UI-Vue/Semantic-UI-Vue#107]
I have some Vue templates that I originally used with semantic UI without semantic-ui-vue. The checkbox labels originally had child elements, like so:

    <label :for='candidate_source.id'>
      <i :class="candidate_source.brand.toLowerCase() + ' icon'"></i>{{ candidate_source.brand }} Exp: {{candidate_source.exp_month}}/{{candidate_source.exp_year}} {{ candidate_source.last4 }}
    </label>

Unfortunately, the label property of the sui-checkbox component is treated as a string type. What's the recommended approach when properties might have child elements? I see the React wrapper for Vue has a notion of subcomponents that can be shortened into attributes when the content is just a string or simple scalar value, but I'm not sure i've spotted an example of that in this project.

I'd be happy to attempt implementing a patch to support this, but I'd like to make sure I understand how this project wants to handle this kind of case generally before trying my hand at that.

**Comment by JasonTrue** [comment]
I think this technically resolves the issue. One caveat worth considering, I think, is that it's probably desirable to have arbitrary slots aside from the label one. For example, in conventional HTML, it's not unheard of to have

    <div class="ui button checkbox">
      <input type=checkbox />
      <label onclick="handleClick()"><i class="visa icon"></i>Card Details</label>
      <button onclick="deleteAction()"><i class="trash icon"></i>Delete</button>
    </div>

However, I don't know enough about the Semantic-UI community to know whether this is considered bad form or not.

**Comment by ArStah** [comment]
I think that checkbox must as simple as possble and contain only the checkbox and label to it, this is how it goes in semantic-ui. If you want to add any other behavior to it - you can create a wrapper around it, since, for examle, deleting action is not related to checkbox, it is an action from your application.. sorry for my bad english)
```html
<div v-for="({label, icon}, id) in checkboxes" >
  <sui-checkbox v-model="checked"><sui-icon :name="icon" /> {{ label }}</sui-checkbox>
  <sui-button negative icon="trash" @click.native="() => checkboxes.splice(id, 1)" />
</div>

<script>
export default {
  data: () => ({
    checkboxes: [
     { icon: "visa", label: "Visa" },
     { icon: "mastercard", label: "Mastercard" },
    ],
    checked: [],
  })
}
</script>
```

**Comment by JasonTrue** [comment]
OK, I can agree with that assessment. I had somewhat sloppy HTML at first, but this kind of approach works for me.
