### ISSUE TITLE
Dropdown doesn't work with vue-router links

### ISSUE THREAD

**Issue by TwoFistedJustice** [Semantic-UI-Vue/Semantic-UI-Vue#108]
I tried inserting a vue-router `<router-link>` into a dropdown that I copied from the docs. At first it displayed the link, but then the link disappeared and would not come back. While it was displayed the link worked as expected.

The disappearance seems to be triggered when I edit anything within the `<sui-dropdown-menu>`.
I'm using it with webpack-simple.

I can duplicate the problem by removing the router link, reloading the app, and then re-inserting the router-link.

Here is the dropdown code:

`<sui-dropdown
        class="teal"
        text="Save"
        :button="true"
        :floating="true"
      >
        <sui-dropdown-menu>
          <sui-dropdown-item>
              <router-link v-if="isAuthenticated"
                           to="adminHouse"
                           exact><a>House</a></router-link>
          </sui-dropdown-item>
          <sui-dropdown-item>Remove Post</sui-dropdown-item>
          <sui-dropdown-item>Hide Post</sui-dropdown-item>
        </sui-dropdown-menu>
      </sui-dropdown>`

**Comment by ArStah** [comment]
If you use `router-link` - you don't need to put `<a>` inside

**Comment by mariolamacchia** [comment]
@TwoFistedJustice it would be so much easier if we could see it in a jsfiddle. Do you think you could reproduce it? https://jsfiddle.net/pvjvekce/

**Comment by TwoFistedJustice** [comment]
I don't think I can reproduce it in a fiddle.

However I did put it into a repo. It should be pretty easy to set up. It uses vue-cli and webpack-simple with a very simple firebase/axios implementation. I  added set up instructions to src/config.js

https://github.com/TwoFistedJustice/sh8-semantic-ui-vue

The code in question is found in src/Header.vue right at the top of the file.

I made the changes you all suggested. Here's what I learned: If I set isAuthenticated to true in the data property of Header.vue, the router-link always shows. If I use the vuex mapGetter then it works for a little while and then disappears. However, I have it duplicated without semantic-ui in the same file, and that one works as expected. 

Header.vue is the only file with anything semantic-ui related as this is just me trying it out on an existing project.

**Comment by ArStah** [comment]
@TwoFistedJustice 
![image](https://user-images.githubusercontent.com/30985699/36328990-efea0cd2-136c-11e8-9489-7eea9bd0a9ab.png)

**Comment by ArStah** [comment]
@TwoFistedJustice don't see any problems there. It is supposed to be dessapeared when `isAuthenticated` === `false`

**Comment by ArStah** [comment]
Maybe i don't understand something... can you make demonstrating video?

**Comment by TwoFistedJustice** [comment]
Yes but it disappears whether the getter returns true or false.

I have the same router link with the same v-if below  and that one displays when the semantic-ui one disappears.

Give me a few minutes, I'll refactor it with a new firebase data store you can use for testing.

**Comment by ArStah** [comment]
@TwoFistedJustice now i see the issue, that's weird

**Comment by TwoFistedJustice** [comment]
Here you go, this should work out of the box. This has an active firebase datastore. I plan to delete the firebase project once this issue is closed.

You'll need to log in once you run the project.

log in: "sandy@christmas.com"
pass: "hghghg"

https://github.com/TwoFistedJustice/sh8-semantic-ui-vue

**Comment by ArStah** [comment]
It is not a problem with `router-link` but with any dynamic `dropdown-item`

**Comment by ArStah** [comment]
Figured that out. I'll include fix to #101

**Comment by ArStah** [comment]
Here is JSFiddle to see bug https://jsfiddle.net/pvjvekce/77/
