### ISSUE TITLE
Clasess function issue

### ISSUE THREAD

**Issue by ArStah** [Semantic-UI-Vue/Semantic-UI-Vue#114]
Hi @mariolamacchia, i've found an issue with current behaivor of [classes function](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/9857eb4cf7b8cb14a0de90a942655be7bfd3410b/src/lib/utils.js#L3).
We need do not filter classes by `uniq` funciton because in [some cases](https://semantic-ui.com/collections/grid.html#significant-word-order) there can be a combinations of classes like `left floated` and `left aligned`, so uniq function will make it `left floated aligned` which will be wrong.
Do you have any reason do not delete `uniq` function usage?
If not i'll make a PR
Thanks

**Comment by ArStah** [comment]
Another example https://semantic-ui.com/collections/grid.html#manual-tweaks

**Comment by mariolamacchia** [comment]
Right I'll remove the `uniq`, thanks for noticing
