### ISSUE TITLE
sui-button breaks event

### ISSUE THREAD

**Issue by filtercake** [Semantic-UI-Vue/Semantic-UI-Vue#121]
https://github.com/filtercake/piggyback/blob/b03684858594b63395218c3a9e9dd8f8cb783207/src/components/TodoExample/Todos.vue#L9

besides using a `sui-button` instead of a `button` the two are the same.

to reproduce you should hopefully be able to clone https://github.com/filtercake/piggyback/, run it vea `npm start`and see it in the "TodoExample".

there are no console errors or the like.

lmk me know if there is any other info needed to debug...

**Comment by ArStah** [comment]
For now you have to use `.native` modifier in order to make it work, see #59. But it will be fixed in next release (#118)

**Comment by filtercake** [comment]
awesome, thx for the quick reply! <3
