### ISSUE TITLE
Multiple selection search dropdown bug

### ISSUE THREAD

**Issue by ArStah** [Semantic-UI-Vue/Semantic-UI-Vue#124]
There is a bug with multiple selection dropdown with search. When there is no choosen values, and you choose first time - dropdown closes, because it loses focus and `closeOnBlur` is triggered. This is [known issue](https://github.com/vuejs/vue/issues/6966) in vue, but maybe we can do some hack until it will be fixed in Vue? 
As note: if put search input before multiple values labels - it works like expected.
Any ideas?

**Comment by mariolamacchia** [comment]
Maybe "disabling" the blur handler just after the click will work. Any better ideas?

**Comment by ArStah** [comment]
@mariolamacchia i've tried that, didn't help. The problem is that in search dropdown the search input must be focused after any action, and after the first option is choosed - because of the vue bug, search input is deleting from DOM and creating again, which causes focus losing. We can do focus on input after some timeout, but i don't think it's a good idea

**Comment by ArStah** [comment]
It works if do
```
setTimeout(() => this.focusSearch());
// or
this.$nextTick(() => this.focusSearch());
```
I think the second solution is better, what do you think?
