### ISSUE TITLE
sui-input bindings are broken

### ISSUE THREAD

**Issue by doublemarked** [Semantic-UI-Vue/Semantic-UI-Vue#125]
I believe this is related to changes in Vue release 2.5.x, but essentially the most rudimentary v-model binding on sui-input is not working. For example,

```<sui-input v-model="username" />```

You can see it broken directly in the Semantic-UI-Vue docs:
    https://semantic-ui-vue.github.io/

Click into the Search input ("Start typing...") on the left sidebar and your input will be replaced with `[object InputEvent]`.

Potentially related issue: https://github.com/vuejs/vue/issues/7042

**Comment by ArStah** [comment]
Hi. Thanks for reporting.
This bug is related to the recent solution found to resolve the #59 issue (PR #118).
Fortunately - we've considered preventing events from passing to root of the component, so we already have a solutio and it will be applied soon

**Comment by mariolamacchia** [comment]
Fixed in v0.1.12
