### ISSUE TITLE
Increase code coverage up to 30%

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#13]
[![codecov](https://codecov.io/gh/Semantic-UI-Vue/Semantic-UI-Vue/branch/master/graph/badge.svg)](https://codecov.io/gh/Semantic-UI-Vue/Semantic-UI-Vue) 
Any unit test is welcome.

Here is an example on how to test a component: https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/test/specs/elements/Button/Button.spec.js

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by dillonchanis** [comment]
Looks fun! I'll give it a shot and start small with writing some tests for Icons.

**Comment by olitaylor** [comment]
I'm up for helping with this as well, I'll start with the container element.

**Comment by dmitriytat** [comment]
I am going to write tests for Image component.

**Comment by olitaylor** [comment]
I'll take a look at writing a test for the Loader element.

**Comment by alexandrebarbaruiva** [comment]
I'll take a look too! But why only 30%?

**Comment by olitaylor** [comment]
@alexandrebarbaruiva Do you know which one your going to work on? Just so I don't do the same element :)

**Comment by alexandrebarbaruiva** [comment]
Button!

**Comment by olitaylor** [comment]
Okay cool, I'll go for the Flag and the Header 👍

**Comment by olitaylor** [comment]
#30 Added PR for Flag, Loader and Header specs.

**Comment by mariolamacchia** [comment]
> I'll take a look too! But why only 30%?

@alexandrebarbaruiva 30% is small enough for a single issue. Once we reach 30%, I'll open separate issues for each part that is missing tests :)

**Comment by tesarwijaya** [comment]
hello, i'd like to contribute regarding this issue.
i just started working on Card view, but i have faced with eslint issue. whenever i run npm test, eslint give me an error ```Expected linebreaks to be 'LF' but found 'CRLF'``` what should i do? i am using vscode on win8
