### ISSUE TITLE
Sidebar pusher doesn't seem to be working

### ISSUE THREAD

**Issue by zywind** [Semantic-UI-Vue/Semantic-UI-Vue#133]
I am not sure if I'm using the sidebar the correct way, but here's how I do it: 
```html
    <sui-sidebar animation="push" class="inverted" :visible=visible>
      <!-- links -->
    </sui-sidebar>
    <sui-sidebar-pusher :dimmed="true">
        <div>
          <button class="ui button" @click="toggleMenu">Menu</button>
        </div>
      <!-- site content -->
    </sui-sidebar-pusher>
```

```js
export default {
  name: 'Home',
  data: () => ({
    visible: false
  }),
  methods: {
    toggleMenu: function () {
      this.visible = !this.visible
    }
  }
}
```

The menu is properly displayed when I click the "Menu" button. The only problem is that the pusher is not dimmed and is not responding to clicks, though its class seems to be correct "pusher dimmed".  Perhaps there is more js code to be added to the pusher?

And what is pushable? It seems semantic 2.3 doesn't use pushable.

**Comment by ArStah** [comment]
Hi. 
1. Since pusher and sidebar have no connection to each other - you have to put `onClick` event listener on `pusher` that will set `visible = false`;
So, from my thoughts you have to do like this:
```vue
   <sui-sidebar animation="push" class="inverted" :visible=visible>
      <!-- links -->
    </sui-sidebar>
    <sui-sidebar-pusher :dimmed="visible" @click="visible = false">
        <div>
          <button class="ui button" @click.prevent="toggleMenu">Menu</button>
        </div>
      <!-- site content -->
    </sui-sidebar-pusher>
```

2. `Pushable` is the element, where pusher and sidebar must be placed if you want to do sidebar not in context of body, but in context of some container, see [example](https://semantic-ui.com/modules/sidebar.html#using-a-custom-context). Since in Vue you can't use multiple elements in root of component - it is not possible to put pusher and sidebar directly in body, so anyway you have to use pushable component to wrap it, even if pushable covers body.

**Comment by zywind** [comment]
Thank you so much for the explanation! I did some additional modification on your code because my menu button is contained in the pusher and whenever the button is clicked the pusher also is clicked. So I have to cancel the event bubbling for that event. 

I'm pasting my code below. Perhaps it will be helpful for others.

```html
<sui-sidebar-pushable>
  <sui-sidebar animation="overlay" class="inverted" :visible="visible">
    <!-- links -->
  </sui-sidebar>
  <sui-sidebar-pusher :dimmed="visible" @click="toggleMenu">
    <div class="ui container" style="margin-top: 60px;">
      <div>
        <button class="ui button" @click="toggleMenu">Menu</button>
      </div>
      <!-- site content -->
    </div>
  </sui-sidebar-pusher>
</sui-sidebar-pushable>
```

```js
export default {
  name: 'Home',
  data: () => ({
    visible: false
  }),
  methods: {
    toggleMenu: function (event) {
      if (!event.target.classList.contains('pusher')) {
        event.cancelBubble = true
      }
      if (!event.target.classList.contains('pusher') ||
          event.target.classList.contains('dimmed')) {
        this.visible = !this.visible
      }
    }
  }
}
```

**Comment by ArStah** [comment]
Oh, i've confused modifier `.prevent` with `.stop`. I think it's enought:
```html
<sui-sidebar-pushable>
  <sui-sidebar animation="overlay" class="inverted" :visible="visible">
    <!-- links -->
  </sui-sidebar>
  <sui-sidebar-pusher :dimmed="visible" @click="visible = false">
    <div class="ui container" style="margin-top: 60px;">
      <div>
        <button class="ui button" @click.stop="visible = false">Menu</button>
      </div>
      <!-- site content -->
    </div>
  </sui-sidebar-pusher>
</sui-sidebar-pushable>
```
```javascript
export default {
  name: 'Home',
  data: () => ({
    visible: false
  }),
}
```
This is how it works in my project

**Comment by zywind** [comment]
Yes. That is an elegant solution.  Thank you!
