### ISSUE TITLE
Integration with vee-validate library

### ISSUE THREAD

**Issue by rhamedy** [Semantic-UI-Vue/Semantic-UI-Vue#138]
A newbie to Vuejs and front-end development. I wanted to make use of [vee-validate](https://github.com/baianat/vee-validate) in my Vuejs (with Semantic-UI-Vue) app but, as soon as I add `vee-validate` (as shown below) the field becomes `read-only` and there are no errors.  

```<sui-form-field>
      <p :class="{ 'control': true }">
        <sui-input
        :class="{'input': true, 'is-danger': errors.has('email') }"
        v-validate="'required|email'"
        type="email"
        name="email"
        placeholder="E-mail address"
        icon="user"
        icon-position="left" />
        <span v-show="errors.has('email')" class="help is-danger">{{ errors.first('email') }}</span>
      </p>
    </sui-form-field>
```
Maybe I am not using it in the right way. Is it possible to make use of `vee-validate` with `Semantic-UI-Vue` components? If yes, how to achieve that. If no, are there plans to do this in the future.

**Comment by mariolamacchia** [comment]
Hi @rhamedy, thanks for reporting this issue. There is a problem on our side, I think we are emitting the wrong data with the input event. I'm working on a fix.

**Comment by mariolamacchia** [comment]
Just tested with vee-validate v2.0.0 and semantic-ui-vue v0.2.6 and it works: https://codesandbox.io/s/0mz3nz22z0

Maybe it was an issue with vee-validate. Closing.
