### ISSUE TITLE
Cannot import css as per documentation.

### ISSUE THREAD

**Issue by smatthews1999** [Semantic-UI-Vue/Semantic-UI-Vue#139]
The documentation specifies loading css as [follows.](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue#semantic-ui-css-package)
I get errors when I try this.
`ERROR in ./node_modules/semantic-ui-css/themes/default/assets/fonts/icons.woff
Module parse failed: Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/semantic-ui-css/semantic.min.css 7:127022-127073
 @ ./node_modules/semantic-ui-css/semantic.min.css
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

**Comment by ArStah** [comment]
It's not problem with our package. You have to configure your webpack to be able to import `.css` files

**Comment by smatthews1999** [comment]
It does import css (but not the binary ttf font that the semantic.css imports).  Any ideas on how I can get this to work with vue cli webpack-simple?

**Comment by ArStah** [comment]
Oh, right, can you reproduce your problem [here](https://codesandbox.io/s/n0zwrvj24p)?

**Comment by mariolamacchia** [comment]
@smatthews1999 Did you add the url-loader to your webpack config? https://github.com/webpack-contrib/css-loader/issues/38

**Comment by smatthews1999** [comment]
@mariolamacchia Thanks that was it.
