### ISSUE TITLE
Menu CSS Different from Semantic UI

### ISSUE THREAD

**Issue by yuens1002** [Semantic-UI-Vue/Semantic-UI-Vue#140]
hi there, i noticed Semantic UI's current (since v2.0) menu has this CSS in their doc

```
<div class="ui three item menu">
  <a class="active item">Editorials</a>
  <a class="item">Reviews</a>
  <a class="item">Upcoming Events</a>
</div>
```

Semantic-UI-Vue however outputs this

```
<div data-v-115c3d82="" class="ui menu" widths="3">
  <div class="item">Editorials</div>
  <div class="item">Reviews</div>
  <div class="active item">Upcoming Events</div>
</div>
```

Semantic UI Vue
```
class="ui menu" widths="3"
```
 vs. Semantic UI
```
class="ui three item menu"
```

I'm totally new to this repo and like to know if the intent of this semantic ui port to vue is to make the css output match the official while giving it the vue treatment.  i'd like to offer some help to fix similar issues like this if it is something worth doing for this repo...

**Comment by ArStah** [comment]
Hey, thanks for reporting, really, there is a missing code in Menu component. Fix will be released soon
