### ISSUE TITLE
Dropdown: `disabled` items

### ISSUE THREAD

**Issue by gokaygurcan** [Semantic-UI-Vue/Semantic-UI-Vue#153]
Hi,

Basically it's the same request, so you can check it here with its solution: https://github.com/Semantic-Org/Semantic-UI-React/issues/478

Cheers,
G.

**Comment by ArStah** [comment]
Hi, thanks for notifying)

**Comment by gokaygurcan** [comment]
Hi,
I need this badly if I continue to use Semantic UI Vue and probably will implement it anyways. But yea, you can put it in your list and add in the future maybe.

**Comment by ArStah** [comment]
For sure we need to add this, but for now as a temprorary solution you can just add `disabled` class to dropdown item

**Comment by gokaygurcan** [comment]
Thank you!
