### ISSUE TITLE
Bug with dropdowns, that have common options source

### ISSUE THREAD

**Issue by ArStah** [Semantic-UI-Vue/Semantic-UI-Vue#155]
Here is [codesandbox](https://codesandbox.io/s/mzn0w31919) to see what happening, try to change value in each of them.
@mariolamacchia do you have any ideas WHY?)

**Comment by helmuthdu** [comment]
I can confirm this bug too, having multiple dropdowns with the same datasource causes an unexpected behavior on components, the values are correctly set, but the view became messy.

**Comment by mariolamacchia** [comment]
I don't think the problem is with the common options source: here all the sources are differenthttps://codesandbox.io/s/q98r45vq2q

The v-model is fine. The issue is with textNode, I'm having a look

**Comment by mariolamacchia** [comment]
Apparently, the issue is that the objects inside the collections are the same. If I use different objects it works: https://codesandbox.io/s/62mqy43vqw
