### ISSUE TITLE
Create Embed component

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#16]
Here is the original one: https://semantic-ui.com/modules/embed.html.

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by viettrung9012** [comment]
Let me take a stab on this

**Comment by viettrung9012** [comment]
@mariolamacchia PR is now ready for review

**Comment by mariolamacchia** [comment]
Released in 0.0.28
