### ISSUE TITLE
Mobile navbar is not fixed anymore

### ISSUE THREAD

**Issue by kubica** [Semantic-UI-Vue/Semantic-UI-Vue#166]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

Mobile navbar is not fixed to top anymore:

<img width="580" alt="bildschirmfoto 2018-05-01 um 12 17 35" src="https://user-images.githubusercontent.com/4146400/39469936-2d5d0c74-4d3b-11e8-88b4-2eae70b55f1e.png">

**Expected behavior**

Mobile navbar should be fixed at the top:

<img width="580" alt="bildschirmfoto 2018-05-01 um 12 34 05" src="https://user-images.githubusercontent.com/4146400/39470115-25ff4144-4d3c-11e8-96c7-c6c0d9d00d6a.png">

**Minimal reproduction of the problem with instructions**

Current demo page has the same issue.

**Solution**

A solution would be to add "fixed"-Class to mobile navbar element but idk how to manage this without changing the lib itself.

For the moment setting the version to 0.2.5 helps.

**Comment by mariolamacchia** [comment]
Thanks for submitting. That's just a missing type in the Menu's props. I added the fix to #165
