### ISSUE TITLE
Dropdown allowAdditions

### ISSUE THREAD

**Issue by mitom** [Semantic-UI-Vue/Semantic-UI-Vue#168]
Is the ability to add [user entries into dropdowns](https://semantic-ui.com/modules/dropdown.html#tagging-and-user-additions) supported in some way? It seems the multi select and search are, but I could not find any indication of user additions :(

Thank you!

**Comment by ArStah** [comment]
Hi, we haven't implemented this feature yet. Feel free to open a PR ;)

**Comment by mitom** [comment]
Thanks for the quick response! There are some minor behavioural aspects I'd like to change and it would be good to get your opinion before I get to it.

At the moment, if you type in a search and press enter nothing happens. This is different from the original behaviour due to the fact that that version will always select the first match, and therefore pressing enter on a search will pick that. This can get a bit confusing once adding user defined elements comes in, since if one types in `alab` and `Alabama` pops up, pressing enter will still select `alab`.  I'd like to change this so that if there is a match, the first filtered option will be selected.

On a similar note, pressing enter does not reset the `filter`, but it will close the dropdown. This means that if you search `alab` and `Alabama` pops up and you press `down` to select it then `enter` to add it, the dropdown selects `Alabama`, closes and loses focus and leaves the typed in `alab` in it. I'd like to fix/change this as well so that selecting a value by pressing `enter` will clear the filter, maybe even keep the dropdown focused if it's `multiple`?

Do you think it's OK to make those changes?

**Comment by ArStah** [comment]
For sure we should make any changes needed to implement original behavior. I agree on the behavior to choose first option on pressing **Enter**, but i'm not facing other problems, that you've described. Mean, that, when you search something and press **enter** in regular `search selection dropdown` - it chooses selected option, clears filter and closes dropdown. In `search multiple selection dropdown`  it just don't clear filter, as you noted, but dropdown doesn't closes(just checked it in [docs](https://semantic-ui-vue.github.io/#/modules/dropdown)). If you facing such problems, can you, please, provide a [codesanbox](https://codesandbox.io/s/n08n0krolj) demonstrating this?

Thanks

**Comment by mitom** [comment]
I've reported that as a separate issue in #169 I think we should continue that conversation there. Meanwhile, I've submitted a PR for this although it's not complete yet - tests are outstanding and quite frankly I am not sure if it covers all aspects correctly, but at least the basis of it works.

**Comment by mariolamacchia** [comment]
Closed by #170
