### ISSUE TITLE
Dropdown additions

### ISSUE THREAD

**Issue by ZeroSoulEater** [Semantic-UI-Vue/Semantic-UI-Vue#175]
Hey,

two things with the dropdown addtions

1. The [doku](https://semantic-ui-vue.github.io/#/modules/dropdown) is wrong in one point. In the Props section it is called **allowAdditions** and if you take a look at the exampels it is used as **allow-additions**

2. The addtions option is not working at all for me
Currently Im using it as the folloing:
```
    <sui-dropdown
          multiple
          fluid
          :options="defaultTags"
          placeholder="Tags"
          search
          selection
          allowAdditions
          v-model="currentTags"
    />
```

And if I typ something in the search bar it shows the "No results found" and I cant add my custom Tag

**Comment by ArStah** [comment]
1. This is how Vue works, you can define prop in `camelCase` or `kebab-case` and use in templates:
 - `kebab-case` when prop is defined with `camelCase` or `kebab-case` 
 - `camelCase` when prop is defined with `camelCase` 
see [docs](https://vuejs.org/v2/guide/components-props.html#Prop-Casing-camelCase-vs-kebab-case)
2. Please, reproduce your bug by forking [this codesandbox](https://codesandbox.io/s/n08n0krolj)

Thanks

**Comment by ZeroSoulEater** [comment]
oh, sorry Im new to vue thanks for the explantaion. 👍 

I can close this, while looking for the error I saw you just add this feature like 6 days ago and I startet this project like 8 days ago and did not update… so my bad I apologize for this!
