### ISSUE TITLE
Checkbox attribute 'disable' does not correctly disable checkboxes 

### ISSUE THREAD

**Issue by amlang** [Semantic-UI-Vue/Semantic-UI-Vue#195]
From the documentation:
![2018-07-08 10 18 12](https://user-images.githubusercontent.com/1733706/42418056-8f9eaae0-8298-11e8-8f24-4ecca517083d.gif)

Checkbox is also not disabled if boolean is true (```disable='true'``` or ```:disable='true'``` or ```disable={{true}}```)

**Comment by ArStah** [comment]
closed via #196
