### ISSUE TITLE
[Error] with Nuxt : module parse failed

### ISSUE THREAD

**Issue by Amaurgit** [Semantic-UI-Vue/Semantic-UI-Vue#202]
Hello there,

I'm trying to use sui-modal in a monofile component with Nuxt and I'm can't get out of this :
`ERROR in ./node_modules/semantic-ui-vue/src/modules/Modal/Modal.jsx
Module parse failed: Unexpected token (159:6)
You may need an appropriate loader to handle this file type.
|   render() {
|     return (
|       <div
|         ref="dimmer"
|         class={
 @ ./node_modules/babel-loader/lib?{"babelrc":false,"cacheDirectory":true,"presets":[["D://ut//AA_Workspace//WebStorm//pupitre-nuxt//node_modules//babel-preset-vue-app//dist//index.common.js",{"targets":{"ie":9,"uglify":true}}]]}!./node_modules/nuxt/node_modules/vue-loader/lib/selector.js?type=script&index=0!./pages/formulaire-rdv.vue 77:0-63
 @ ./pages/formulaire-rdv.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js`

Do you have any idea ? 
Thank you :)

**Comment by ArStah** [comment]
What version of nuxt do you use?

**Comment by Amaurgit** [comment]
Hello ArStah,

Extract from my package.json :

    "nuxt": "^1.0.0",

Thanks :)

**Comment by alexschlie** [comment]
Same for me without nuxt

> error  in
> ./node_modules/semantic-ui-vue/src/elements/Button/Button.jsx`
> 
> Module parse failed: Unexpected token (134:6) You may need an
> appropriate loader to handle this file type.
>
>     const button = (
>       <ElementType
>         {...this.getChildPropsAndListeners()}
>                class={classList}

**Comment by ArStah** [comment]
@Amaurgit You have to use `nuxt@^1.2.0`
@alexschlie for making it work you have to add loader for `.jsx` files to your webpack config

**Comment by Amaurgit** [comment]
@ArStah Thank you so much :)
Seems that the Nuxt archetype is based on nuxt@^1.0.0
