### ISSUE TITLE
Add support for partial import

### ISSUE THREAD

**Issue by rajagopalx** [Semantic-UI-Vue/Semantic-UI-Vue#206]
Let's assume, I want to use only progress component. Is there any way to import progress component only?

**Comment by ArStah** [comment]
Hey, for now you should do it like this: 
```javascript
import Dropdown from 'semantic-ui-vue/dist/commonjs/modules/Dropdown/Dropdown';
// or, if your project can handle importing .jsx files
import Dropdown from 'semantic-ui-vue/src/modules/Dropdown/Dropdown.jsx';
```
But, i think we have to do it little bit more convenient, @mariolamacchia what do you think?

**Comment by mariolamacchia** [comment]
Yeah, probably. I'd say it should be something like:

`import { Progress } from 'semantic-ui-vue/modules/progress';`

Also it should be already transpiled

**Comment by rajagopalx** [comment]
Thanks for reply.  I got the error Unknown custom element: <sui-progress> - did you register the component correctly?  https://codesandbox.io/s/6w0pz29903

**Comment by mariolamacchia** [comment]
You can't use `Vue.use` like that. You need:
```
new Vue({
  el: "#app",
  components: { App },
  template: "<App/>"
});
```

**Comment by mariolamacchia** [comment]
If you don't want to import it in every component, you can write in your app.js:

```js
import Progress from "semantic-ui-vue/dist/commonjs/modules/Progress/Progress";

// ...

Vue.component(Progress.name, Progress);
```

**Comment by rajagopalx** [comment]
Thanks a lot. Is there any way to import CSS only for Progress component?

**Comment by rajagopalx** [comment]
Thanks @ArStah @mariolamacchia 💯

**Comment by Joshfindit** [comment]
Just a quick reminder about renaming since it helped me:

``` javascript
import Progress from "semantic-ui-vue/dist/commonjs/modules/Progress/Progress";

// ...

  components: {
    'sui-progress': Progress
  },
```

**Comment by mariolamacchia** [comment]
Added in v0.9.0
