### ISSUE TITLE
Missing props for dropdown component

### ISSUE THREAD

**Issue by domcorvasce** [Semantic-UI-Vue/Semantic-UI-Vue#209]
I was working on the "fixed menu layout" when I noticed some props are missing, like:

- [x] simple: A simple dropdown can open without Javascript.
- [x] upward: Controls whether the dropdown will open upward.

You can see the full list here: https://react.semantic-ui.com/modules/dropdown/

**Comment by ArStah** [comment]
Hey, thanks for this issue. Agree about `simple` prop, we should add it, but disagree about `upward` prop, since we have little bit different approach to this and already have prop `direction` which you can use to set upward direction
