### ISSUE TITLE
Create Tab component

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#21]
Here is the original one: https://semantic-ui.com/modules/tab.html.

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by jamesday7** [comment]
Having a look at this for you :)

**Comment by tesarwijaya** [comment]
i'll take this if no one had.

**Comment by mariolamacchia** [comment]
@tesarwijaya thanks!

**Comment by tesarwijaya** [comment]
i have created this component but i need you to review my pull request #65 first.

**Comment by kuroljov** [comment]
What is the status of this PR and this project overall? Is it going anywhere?

**Comment by mariolamacchia** [comment]
There isn't a PR. Nobody is working on it right now.

Please, understand this is an open source project: nobody **has** to do anything and the entire community can contribute.

Getting questions like "where is this project going" is so frustrating. If you need this feature, consider contributing.

**Comment by kuroljov** [comment]
@mariolamacchia I've mistaken this with PR. Sorry. No reason for a rant here

**Comment by afparsons** [comment]
Good work everyone. 
Am I missing something, or is this currently broken? I can file a bug report need-be.

The examples given on the website do not function as expected when copied.

**Comment by viktor-ku** [comment]
@afparsons Open the new issue with detailed description

**Comment by viktor-ku** [comment]
@mariolamacchia you can close this issue now I think
