### ISSUE TITLE
Dropdown menus overlap

### ISSUE THREAD

**Issue by ghostoy** [Semantic-UI-Vue/Semantic-UI-Vue#223]
`simple` menus hide & popup on mouse in & out as expected. But neighbor menus overlap with each other if I **clicked one and move mouse onto another**.
![snapshot](https://user-images.githubusercontent.com/471928/44194034-5c79f500-a167-11e8-8b3d-bd38a97a4e21.png)

**Comment by MessineseGianluca** [comment]
Can't reproduce anymore.
