### ISSUE TITLE
Using Fontawesome Pro icons

### ISSUE THREAD

**Issue by Extarys** [Semantic-UI-Vue/Semantic-UI-Vue#225]
I love using Semantic UI with VueJS :)

Is there an easy way I could use Fontawesome Pro icons?

For example, I imported everything in my main.js file like so:
```
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import { library } from '@fortawesome/fontawesome-svg-core'
import { faPlay } from '@fortawesome/pro-light-svg-icons'
library.add(faPlay)
Vue.component('font-awesome-icon', FontAwesomeIcon)
```

And I'd like to use it like so:
```
        <sui-button-group icons>
            <sui-button :icon="['fal', 'play']"/>
            <sui-button icon="pause"/>
            <sui-button icon="stop"/>
        </sui-button-group>
```

I would like to avoid modifying the module so packages update are going to be easier.

Thanks!

**Comment by douglasg14b** [comment]
@Extarys Fomantic UI has a script that generates the necessary bits for font-awesome pro ehre: https://github.com/fomantic/icon-script

Hammy makes mention of it here: https://github.com/fomantic/Fomantic-UI/issues/319#issuecomment-461724681

**Comment by mariolamacchia** [comment]
Duplicate ok #345
