### ISSUE TITLE
Adding internationalization (I18n support)

### ISSUE THREAD

**Issue by sinkersan** [Semantic-UI-Vue/Semantic-UI-Vue#236]
Hello!

I really love how you did realization of Semantic UI for Vue.
But unfortunately, I found out that it does not support I18n.
Do you have any plans to adding translation support? Maybe trough props or something like this.

I think this is a big issue for those who want to use your components across the world.

**Comment by mariolamacchia** [comment]
What do you mean when you say it doesn't support i18n?

This is a component library, it doesn't handle content. If you need i18n, you should use a separate library, like [vue-i18n](https://github.com/kazupon/vue-i18n)

**Comment by sinkersan** [comment]
Hi. 
Sorry, I think I was should add a link with an example.
I found in the Dropdown module with the search option that it shows text "No results found" in case if the filter result is empty.
https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/ce47b2a65e16795f1a8acc31d29ea648e862749d/src/modules/Dropdown/Dropdown.jsx#L192

To be honest, I'm not sure that other components have a text like this that will be shown for the user in the UI. But I think all of those components should have options to override this text. 
So in case when the developer needs to have Internationalization in the project he will be able to pass proper text.

I hope now it more clear what I meant for the first time.

Also, the React implementation of Semantic UI Dropdown has the **noResultsMessage** prop with default value.
https://github.com/Semantic-Org/Semantic-UI-React/blob/3e4243a176b53c5f3192ff840f09f8c1ed2d147d/src/modules/Dropdown/Dropdown.js#L361

**Comment by mariolamacchia** [comment]
Yes makes sense
