### ISSUE TITLE
Allowing any value type in dropdown

### ISSUE THREAD

**Issue by Shir0kamii** [Semantic-UI-Vue/Semantic-UI-Vue#238]
Hello,

It would be great to allow any type in dropdown values. I'm currently using it with objects and it's raising errors. :(

If you agree to the change, I can make a PR.

Thanks for the work you've done!

**Comment by ArStah** [comment]
Yeah, i think it's a good idea)

**Comment by mariolamacchia** [comment]
Released in 0.4.1
