### ISSUE TITLE
How to customise active modal

### ISSUE THREAD

**Issue by rubenberna** [Semantic-UI-Vue/Semantic-UI-Vue#245]
Hi,

I'm using the standard modal for vue and I'm having trouble targeting the active modal box. 

In the CSS devtools, this is the class I should target: 

.ui.standart.modal.transition.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
    background: yellow;
  }

However, though I can manipulate it through the devtools, I can not do so from the Vue file. 

Thanks for your help!

**Comment by mariolamacchia** [comment]
Hi Ruben. Can you share the code of your vue file?

**Comment by rubenberna** [comment]
Hi Mario,

Sure, please see it below. Thanks in advance!

```
<template lang="html">
  <div class="booking">
    <div class="currentUser"
         v-if="currentUser">
         <sui-button  class="booking-button"
                      @click.native="toggle">
                      Make appointment
       </sui-button>
    </div>
    <div v-else>
      <sui-button  class="booking-button"
                   @click="loginFirst">
                   Make appointment
      </sui-button>
    </div>
    <sui-modal v-model="open">
      <sui-modal-content image>
        <sui-image wrapped size="medium"
                   class="booking-image"
                  :src='therapy.image' />
          <sui-modal-description>
            <sui-header class="booking-header">
              <p>{{ therapy.name }}</p>
              <span class="booking-header_close"
                    @click='toggle'>
                    close
              </span>
            </sui-header>
            <div class="booking-description">
              <p>Thank you for choosing the {{ therapy.name }} therapy!</p>
              <p>This treatment is available on {{ therapy.availability.toLowerCase() }} with a price of {{ therapy.price }} per session.</p>
              <p>Would you like to schedule an appointment?</p>
            </div>
            <sui-form class="booking-details">
              <sui-form-field>
                <label>Preferred date</label>
                <input v-model="booking.date" type="date" placeholder="dd.mm.jj">
              </sui-form-field>
              <sui-form-field>
                <label>Phone number</label>
                <input v-model="booking.phone" type="tel" placeholder="0489 555 555">
              </sui-form-field>
              <sui-label v-if='outcome.error'
                         basic color="red" pointing='above'
                         class="notification">
                         {{outcome.errorMsg}}
              </sui-label>
              <sui-button v-if='!outcome.success'
                          primary
                          @click.prevent='validateBooking()'>
                          Schedule appointment
              </sui-button>
              <div v-else
                   class="booking-success">
                   <paragraph size='l'
                              weight='semibold'>
                              Thank you!!
                  </paragraph>
                   <paragraph size='l'
                              weight='semibold'>
                              I will get in touch with you shortly!
                  </paragraph>
              </div>
            </sui-form>
          </sui-modal-description>
      </sui-modal-content>
    </sui-modal>
  </div>
</template>
```

**Comment by mariolamacchia** [comment]
Where is the css bit?

**Comment by rubenberna** [comment]
`<style lang="scss" scoped>
  @import '../../../style/main.scss';

  .booking-button {
    padding: 9px 15px;
    font-size: 11px;
    letter-spacing: .10rem;
    text-transform: uppercase;
    border-right: 1px solid #e5e5e5;
    border-bottom: 1px solid #e5e5e5;
    border-radius: 0px;
    background-color: white;
    font-family: $font-family-p;
    font-weight: $normal;
    transition: all 0.5s;
    &:hover{
      background-color: #f2f3ee;
      border-radius: 4px;
    }
  }

  .booking-image {
    display: flex !important;
    align-items: flex-end;
  }

  .booking-header {
    text-transform: uppercase;
    display: flex;
    justify-content: space-between;
    width: 510px;
    p {
      font-weight: 700;
      letter-spacing: .135em;
    }
    .booking-header_close {
      text-transform: lowercase;
      font-size: 13px;
      cursor: pointer;
      color: $steel;
      &:hover {
        color: $color-text;
      }
    }
  }

  .booking-description {
    margin-top: 23px;
    font-family: $font-family-p;
    color: $color-text;
    font-weight: 300;
  }
  .booking-details {
    max-width: 55%;
    margin-top: 37px;
    display: flex;
    flex-direction: column;
    input {
      height: 23px;
    }
    .notification {
      margin-bottom: 12px;
    }
    .booking-success {

      transition: all 3s;
      color: $success;
    }
  }

  .ui.primary.button {
    background: $white;
    border: 2px solid $green;
    border-radius: 4px;
    color: $color-text;
    width: 79%;
    height: 45px;
    margin-top: 3px;
    &:hover {
    background: $green;
    color: $white;
    }
  }
</style>
`

I've tried targeting the box with a number of classes, none of them really worked:

`.ui.standart.modal.transition.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
    background: yellow;
  }

  sui-modal.transition.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
    background: yellow;
  }

  .modal.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
  }

  .modal.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
  }
  .ui.modal.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
  }

  .modal.ui.modal.visible.transition.ui.active.modal {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
  }

  div.ui.modal.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
  }
  div.ui.modal.transition.visible.active {
    max-height: 59% !important;
    left: 27%;
    top: 25%;
  }`

**Comment by mariolamacchia** [comment]
I would expect it to work, there must be something missing here. I'm going to need an example that reproduces the error. You can use this https://codesandbox.io/s/n08n0krolj

**Comment by mariolamacchia** [comment]
Actually, the reason is that you're using `<style scoped>`. Just remove `scoped`: https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles
