### ISSUE TITLE
Dropdown gives undefined classList error when filteredText undefined

### ISSUE THREAD

**Issue by helariL** [Semantic-UI-Vue/Semantic-UI-Vue#251]
When trying to use `sui-dropdown` with `sui-dropdown-menu` which in return allows for custom search box it goes to overdrive and starts filtering on undefined element. ( This is a bit of a workaroudn to mock filters from semantic-ui )

![screenshot 2018-10-17 at 15 03 09](https://user-images.githubusercontent.com/5609788/47084981-e0ab3000-d21d-11e8-85f1-5e8fefa2d51a.png)

`filteredText` existance should be checked in `toggleFilteredText`

![screenshot 2018-10-17 at 15 07 48](https://user-images.githubusercontent.com/5609788/47085163-6d55ee00-d21e-11e8-8b15-ae640ece001c.png)

**Comment by morficus** [comment]
This issue is no longer present in the latest version.
