### ISSUE TITLE
sui-header center aligned has no effect

### ISSUE THREAD

**Issue by jkeiser** [Semantic-UI-Vue/Semantic-UI-Vue#263]
`sui-header center aligned` doesn't seem to work (though explicitly specifying the class does). [Feature Status](https://semantic-ui-vue.github.io/?ref=madewithvuejs.com#/features) says it's 100% supported but maybe that doesn't include "common attributes"?

[Example on codesandbox](https://codesandbox.io/s/y0084x49pj):

```html
  <sui-container>
    <sui-header as="h1" center aligned>sui-header as h1 center aligned</sui-header>
    <sui-header as="h1" class="center aligned">sui-header as h1 class="center aligned"</sui-header>
  </sui-container>
```

![image](https://user-images.githubusercontent.com/654882/47860482-dfe1d480-ddad-11e8-8c4f-8ef85dc4e9c9.png)

I am using the [semantic-ui npm package version 2.4.2](https://www.npmjs.com/package/semantic-ui/v/2.4.2).

**Comment by mariolamacchia** [comment]
https://semantic-ui-vue.github.io/#/elements/header#text-alignment

It should be `<h1 is="sui-header" text-align="center">`

**Comment by jkeiser** [comment]
Thanks!
