### ISSUE TITLE
Fix docs layout on big screen

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#27]
The white container should be aligned to the left. This happens on big screens (width 1600+px)

![screen shot 2017-10-02 at 3 25 01 pm](https://user-images.githubusercontent.com/6282722/31082146-03cfe972-a786-11e7-95ca-67cff8aa6aea.png)

**Comment by yoksanherlie** [comment]
Me! Let me fix this issue.
This will be my first open source contribution if I can fix this issue! :)

**Comment by mariolamacchia** [comment]
Fixed in 0.0.19
