### ISSUE TITLE
Error with using dropdown menu: event is not defined

### ISSUE THREAD

**Issue by yayromina** [Semantic-UI-Vue/Semantic-UI-Vue#275]
I am trying to use the Dropdown module. When I select an option, the dropdown remains and I get the console error: `ReferenceError: event is not defined`. Even trying to use it exactly as the documentation does yields this error:

```
<template>
<sui-dropdown
   placeholder="Gender"
   selection
   :options="options"
   v-model="gender"
/>
</template>
```

```
data(){
  return {
    gender: '',
    options: [{
      text: 'Male',
      value: 1,
    }, {
      text: 'Female',
      value: 2,
    }],
 }
}
```

I tried passing an event, @click, and received the same result. What am I missing? I am using Nuxt if that makes any difference.

**Comment by mariolamacchia** [comment]
Hi @yayromina, thanks for submitting this issue. What version are you using? I think we fixed this in v0.7.0
