### ISSUE TITLE
Semantic UI Vue doesn't work (Vue CLI 3)

### ISSUE THREAD

**Issue by jpgklassen** [Semantic-UI-Vue/Semantic-UI-Vue#277]
I am writing a web app using Vue CLI 3. I followed the installation instructions for Semantic UI Vue:

1. `npm install semantic-ui-vue --save`
2. In main.js: `import SemanticUI from 'semantic-ui-vue'`
3. In main.js: `Vue.use(SemanticUI)`

In one of my components, I tried adding the "ui" and "input" classes to a div containing a text input:

```
<div class="ui input">
  <input type="text" />
</div>
```

...and nothing happened. The text input doesn't look any different from the default styling.

Also, shouldn't there be a config file somewhere so I can set global variables such as primary color?

**Comment by domcorvasce** [comment]
First, did you add the Semantic UI stylesheet to your index.html?

```html
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.3.0/semantic.min.css">
```

**Comment by scblur869** [comment]
so I have a similar problem with version 0.7.0. but following the same steps as above i get this from my import statement with semantic-ui-vue

```[ts]
Could not find a declaration file for module 'semantic-ui-vue'. '/Users/brad.ross/vueProjects/sui-bank/node_modules/semantic-ui-vue/dist/commonjs/index.js' implicitly has an 'any' type.
  Try `npm install @types/semantic-ui-vue` if it exists or add a new declaration (.d.ts) file containing `declare module 'semantic-ui-vue';` [7016]
module "/Users/brad.ross/vueProjects/sui-bank/node_modules/semantic-ui-vue/dist/commonjs/index"
```

any ideas? I cannot get any sui-* controls to be recognized or registered even though SemanticUI is in my "vue.use" instance..

**Comment by mariolamacchia** [comment]
@jpgklassen as @domcorvasce said, it seems you skipped the [CSS instruction part of the getting started](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue#css).

@scblur869 that seems an error related to typescript. Please, create a new issue with more details on how to reproduce

**Comment by jpgklassen** [comment]
@domcorvasce Thank you, adding that CSS stylesheet to my index.html worked. I found the installation instructions to be a bit unclear. I thought that the CSS stylesheet was optional, for those who only wanted to use the CSS and not the JavaScript. I saw that the Node package contained a lot of CSS stylesheets, so I thought all the CSS I needed was already included. Why is this not the case? Shouldn't installing the Vue plugin via `Vue.use()` be enough to get it working? Perhaps it's just my inexperience, but I've never known any other Vue plugin to require additional steps.

I did not use `sui-input`; adding the "ui" and "input" classes to the parent element, like the [documentation](https://semantic-ui.com/elements/input.html) says, worked just fine (once I added the CSS stylesheet to my index.html). What does `sui-input` do and why isn't it mentioned in the documentation?

Is there a config file somewhere that will let me set global variables such as primary color?

Thanks for your help!

**Comment by mariolamacchia** [comment]
I think you are looking for Semantic UI, not Semantic UI Vue. https://github.com/semantic-org/semantic-ui/

**Comment by mariolamacchia** [comment]
Yes, for the javascript part only of Semantic UI. From the README:

> Installing Semantic UI Vue provides the JavaScript for your components. You'll also need to include a stylesheet to provide the styling for your components.

From your comments, it looks like you only need the CSS. Why do you need a Vue library?

Also, you are confusing our docs:

Semantic UI: https://semantic-ui.com
Semantic UI Vue: https://semantic-ui-vue.github.io/

**Comment by jpgklassen** [comment]
@mariolamacchia I do need the JavaScript as well as the CSS; I just said that I thought that the CSS stylesheet was optional, for those who only wanted to use the CSS and not the JavaScript, and therefore I did _not_ include it in my code.

Thanks for linking me to the correct docs! That's extremely helpful.

Why is the CSS not included in the Vue plugin? Perhaps it's just my inexperience, but I've never known any other Vue plugin to require additional steps beyond `Vue.use()`.

Is there a config file somewhere that will let me set global variables such as primary color?

**Comment by mariolamacchia** [comment]
> I just said that I thought that the CSS stylesheet was optional, for those who only wanted to use the CSS and not the JavaScript, and therefore I did not include it in my code.

Those who only want to use CSS can use Semantic UI, no need to use Semantic UI Vue.

> Why is the CSS not included in the Vue plugin? Perhaps it's just my inexperience, but I've never known any other Vue plugin to require additional steps beyond Vue.use().

Because the CSS part already exists and is maintained in the original Semantic UI.

> Is there a config file somewhere that will let me set global variables such as primary color?

Colors are CSS responsibilities, so you should look at the Semantic UI docs for how to configure themes https://semantic-ui.com/usage/theming.html

**Comment by jpgklassen** [comment]
> Because the CSS part already exists and is maintained in the original Semantic UI.

I see. So we don't want to include it in Semantic UI Vue, because then they might get out of sync?

> Colors are CSS responsibilities, so you should look at the Semantic UI docs for how to configure themes https://semantic-ui.com/usage/theming.html

Okay thanks, I'll try that! So this page of the Semantic UI documentation applies to Semantic UI Vue? I noticed the Semantic UI Vue documentation you linked me to doesn't really talk about themes.
