### ISSUE TITLE
Fomantic UI?

### ISSUE THREAD

**Issue by douglasg14b** [Semantic-UI-Vue/Semantic-UI-Vue#282]
Semantic was forked by the community due to inactivity, and https://github.com/fomantic/Fomantic-UI was formed.

Its had a lot of activity, and plenty of bugs and styling issues are being fixed. Is there any reason to move any styling/components over from Fomantic and shift in that direction? It's moving forward well, and I imagine you'll start to see issues with stylesheet compatibilites as it continues to grow.

Just looking for a discussion on this to hear some opinions.

**Comment by lubber-de** [comment]
Thank you for your interest in Fomantic-UI. 🙂 As a maintainer of Fomantic-UI, I can of course only highly suggest to go into that direction. The recently released v 2.7.1 really has a lot of bugs fixed which have been, in some cases, laying around in SUI for several years (!) 
To benefit from the new features you might have to adjust your vue version of course.

**Comment by mariolamacchia** [comment]
RIght now Semantic UI Vue works with Fomantic UI, unless there are already some breaking changes on the CSS. Therefore, I'm closing this issue as it doesn't need any action.

There is already an open discussion on Gitter, I suggest everyone share their ideas there since it's a better place for this kind of things.

**Comment by douglasg14b** [comment]
@mariolamacchia 

Gitter (and chat in general) is a platform unfit for long-term items and discussions as they are rapidly lost in the chats history and are not discoverable through search engines to new users or users looking for the same thing. All they can find is a github issue with "chat about it on [discord/gitter/slack/irc....etc]. For all intents and purposes the community knowledge that might be generated during a discussion will be lost shortly after.

I think this should stay open, as there WILL be breaking changes as time goes on and semantic falls behind fomantic.
