### ISSUE TITLE
Use Fomantic-UI in README

### ISSUE THREAD

**Issue by Fusseldieb** [Semantic-UI-Vue/Semantic-UI-Vue#285]
At the time of writing, the installer of the "semantic-ui" is [broken on Windows 10](https://github.com/Semantic-Org/Semantic-UI/issues/6642) and also the development on the original project has almost ceased. 
That's where devs forked the project and created a awesome new fork called "formantic-ui", which is basically the same, but newer.

The README of _this_ page says:

> $ npm install semantic-ui --save-dev

> import '../semantic/dist/semantic.min.css';

which led to a lot of headaches, since that installer hangs on Windows 10 and has a lot of other issues, as mentioned above. 

The solution for me was to use following commands:

> $ npm install fomantic-ui --save-dev

> import '../fomantic/dist/semantic.min.css';

And it worked like it should.

I _think_ someone should do a pull request on that README, replacing semantic with fomantic, to solve some issues I mentioned above. I spent 3 hours on that problem.

**Comment by mariolamacchia** [comment]
Closing as it's not an issue related to Semantic UI Vue.

As said several times, we are not going to add Fomantic UI to our README (yet) as that would mean having to support eventual breaking changes from their side.
