### ISSUE TITLE
Error in render function: "TypeError: Cannot read property 'icon' of undefined

### ISSUE THREAD

**Issue by vikramparihar** [Semantic-UI-Vue/Semantic-UI-Vue#289]
```
<sui-dropdown
     fluid
     multiple
     :options="services"
     placeholder="Services"
     selection
     v-model="project.services"
/>
```
Error in render function: "TypeError: Cannot read property 'icon' of undefined

Linux plateform
Version 65.0.3325.146 (Official Build) (64-bit)

**Comment by vikramparihar** [comment]
<sui-dropdown
                                        fluid
                                        multiple
                                        :options="services"
                                        placeholder="Services"
                                        selection
                                        v-model="project.services"
                                        />

**Comment by vikramparihar** [comment]
> ```
> <sui-dropdown
>      fluid
>      multiple
>      :options="services"
>      placeholder="Services"
>      selection
>      v-model="project.services"
> />
> ```
> Error in render function: "TypeError: Cannot read property 'icon' of undefined
> 
> Linux plateform
> Version 65.0.3325.146 (Official Build) (64-bit)

**Comment by anderfernandes** [comment]
I am having this problem right now. What did you do to fix it? Was it something about project.services being a property nested inside of an object?
