### ISSUE TITLE
Maintenance of repository 

### ISSUE THREAD

**Issue by SrPatinhas** [Semantic-UI-Vue/Semantic-UI-Vue#297]
Is this project still maintained or can we say that if we use it, we will not have much more updates?

**Comment by mariolamacchia** [comment]
Hey @SrPatinhas, unfortunately I'm very busy with work and personal stuff in this period. At the moment it's only me, but I'm [looking for other maintainers](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue#looking-for-maintainers): anyone willing to help is more than welcome. 

Yes, the project is active but it's going to move very slowly, unless I find someone else to help me

**Comment by SrPatinhas** [comment]
I saw the [Feature Status](https://semantic-ui-vue.github.io/#/features) and saw that almost every module as something to do, maybe an help on what to do would be easier for any PR and to have something more complete as we go on.

**Comment by mariolamacchia** [comment]
That's a great idea. I'll open a bunch of issues within the next week

**Comment by adavie1** [comment]
@mariolamacchia count me in. I've got quite a bit of experience with Vue and element-ui. I'm planning to transition that project to semeantic-ui, so very happy to help.

**Comment by mariolamacchia** [comment]
Hey @adavie1, that would be great! Contact me on gitter if you are interested in joining. https://gitter.im/mariolamacchia
