### ISSUE TITLE
Add menu size prop

### ISSUE THREAD

**Issue by mrcasablr** [Semantic-UI-Vue/Semantic-UI-Vue#306]
There is a size parameter for menu component in semantic-ui: https://fomantic-ui.com/collections/menu.html#size

I do not see that option exposed in semantic-ui-vue:  https://semantic-ui-vue.github.io/#/collections/menu

How do I go about setting up the menu size using sui-menu component?

Thanks!

**Comment by exoego** [comment]
If I understand correctly, every SUI-Vue component accept `class` or `:class` attribute implicitly.
So `<sui-menu class="large">...` or something will change size of the component

Example is https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/7b87f17816e3b7e9734bbab9ddc730c33fc91e6c/docs/Example.vue#L12-L13
which adds `options-menu` class to `menu` component.
![image](https://user-images.githubusercontent.com/127635/57271552-d58cf400-70ca-11e9-89c3-57310b122ba2.png)

**Comment by mariolamacchia** [comment]
Closing in favour of #392
