### ISSUE TITLE
vue-events conflict: TypeError: this.$options.events[key].bind is not a function

### ISSUE THREAD

**Issue by nocturn3e** [Semantic-UI-Vue/Semantic-UI-Vue#318]
**vue-events@3.1.0**
**semantic-ui-vue@0.8.1**

When the Vue instance uses vue-events, any semantic-ui-vue component produces the following error:

> TypeError: this.$options.events[key].bind is not a function

> [Vue warn]: Error in beforeCreate hook: "TypeError: this.$options.events[key].bind is not a function"

Bug reproduced: https://codesandbox.io/embed/oxjok13625

**Comment by mariolamacchia** [comment]
Duplicate of #161
