### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by jklingen** [Semantic-UI-Vue/Semantic-UI-Vue#321]
I use Vue.js with TypeScript and Babel and experience problems with integrating Semantic UI Vue.

After adding a Sui* component, e.g. like this: 

    import SuiButton from 'semantic-ui-vue/src/elements/Button/Button';

    @Component({
      components: {SuiButton}
    })

the application breaks with an error like 

     error  in ./node_modules/semantic-ui-vue/src/elements/Button/Button.jsx

    Module parse failed: Unexpected token (134:6)
    You may need an appropriate loader to handle this file type.
    |
    |     const button = (
    >       <ElementType
    |         {...this.getChildPropsAndListeners()}
    |         class={classList}

I have created a minimal setup here: https://github.com/jklingen/vue-with-semantic-ui-vue

Am I using it wrong? Shouldn't the components be pre-transpiled to JS? Or otherwise, what would be the recommended way to make my application do the transpilation? Is this something we should add to the documentation of semantic-vue-ui?

Note aside: if I remove `components: {SuiButton}` and the import, the application works as intended, however an error is logged whenever I run unit tests.

Thanks in advance.

**Comment by mariolamacchia** [comment]
Babel doesn't transpile node_modules by default. Try to import `semantic-ui-vue/dist/commonjs/elements/Button/Button` instead
