### ISSUE TITLE
Second dropwdown don't show.

### ISSUE THREAD

**Issue by Adrek** [Semantic-UI-Vue/Semantic-UI-Vue#327]
The dropdown menu does not show the second level of dropdown. That is, if you click on the tool icon, the sub-menu is displayed. Up to here all very well, but if you click on the word "New" the second dropdown does not appear

https://semantic-ui-vue.github.io/#/collections/menu
(First Menu)

**Comment by mariolamacchia** [comment]
Duplicate of #293
