### ISSUE TITLE
Helping out

### ISSUE THREAD

**Issue by Badidzetai** [Semantic-UI-Vue/Semantic-UI-Vue#330]
Heyah, 

I've been using sui-vue for a while now and would like to lend a hand to this open source project that makes my life so much easier.

I'm used to using vue-semantic, and semantic in general, and writing VueJS.

What can be done to help ?

**Comment by mariolamacchia** [comment]
Hi @Badidzetai, that's great!

Any help is really appreciated. Feel free to submit a PR with a fix or a feature, then I'll add you as a collaborator 😃
