### ISSUE TITLE
Image component wont load any image

### ISSUE THREAD

**Issue by CleitonCardoso** [Semantic-UI-Vue/Semantic-UI-Vue#331]
I'm facing an anoying issue with this component and I cant figure it out what's happening.

![image](https://user-images.githubusercontent.com/2112379/60185455-59787800-9800-11e9-8b7d-5c58e6e700f9.png)

As you can see on the image above, I'm using sui-image and passing the file path exactly like I'm passing to img. 

That's the result:

![image](https://user-images.githubusercontent.com/2112379/60185655-abb99900-9800-11e9-910d-07c84dcaa25a.png)

Notice that img works properly, also sui-button, but sui-image don't.

The final HTML is like this:

![image](https://user-images.githubusercontent.com/2112379/60185880-18cd2e80-9801-11e9-838a-a7c3e2e61c6d.png)

What am I missing here?

Since now, thaks for your help.

**Comment by mariolamacchia** [comment]
As you can see in the DOM, the path in the `img` changes to something else. There is probably something on your build that replaces the file names and it only looks for `<img>` tags
