### ISSUE TITLE
[Accordion] content inside accordion not working properly

### ISSUE THREAD

**Issue by pumano** [Semantic-UI-Vue/Semantic-UI-Vue#339]
Accordion content broke styles for inside component and also broke behaviour.

I'm use [hooper](https://github.com/baianat/hooper) image gallery, and that gallery works perfectly, except in `sui-accordion-content`.

Check reproducible example here: https://codesandbox.io/s/vue-template-wdxn8

Also I find when I resize browser - all is OK, and start working, but, not working by default.

**Comment by mariolamacchia** [comment]
Hi @pumano. I'd say this is probably an issue on the hooper side, I don't see how anything in the accordion could be breaking it. I can indeed reproduce it, but I'd need to debug the hooper's code to see what's wrong. 

Have you tried submitting an issue on their repo?

**Comment by pumano** [comment]
Yes, I agree not a problem on semantic UI side. So we can close issue
