### ISSUE TITLE
Why sui dont working in cordova?

### ISSUE THREAD

**Issue by BDAinc** [Semantic-UI-Vue/Semantic-UI-Vue#340]
Hi guys! 

I used vue-cli-plugin-cordova to generate the application. 

I installed Semantic-UI-Vue in the project. 

main.js looks like this 

```
import Vue from 'vue'
import App from './App.vue'
import SuiVue from 'semantic-ui-vue';

Vue.config.production Type = false
Vue.use(SuiVue)

new Vue({
  render: h => h(App),
}).$mount('#app')
```

After restarting the application in the browser, the test code in the components did not work. 
There are no errors in the developer tool and console

What could be the problem?

**Comment by tripflex** [comment]
First issue I see is that:
`Vue.config.production Type = false`

Should be:
`Vue.config.productionTip = false`

**Comment by mariolamacchia** [comment]
Closing as the description doesn't provide enough information. Please, reopen it with more detail if you are still having the problem.
