### ISSUE TITLE
Validator for prop "state" should allow varriant "loading", it's working but log error. SenimaticUI accept state "loading" in form.

### ISSUE THREAD

**Issue by THBAndrey** [Semantic-UI-Vue/Semantic-UI-Vue#342]
`[Vue warn]: Invalid prop: custom validator check failed for prop "state".`
On this line
`this.state = 'loading'`
But this work and show a loading indicator

**Comment by domcorvasce** [comment]
I'm pushing a PR in order to fix it.

Currently, Semantic UI Vue offers **shortcut props** for representing the form's state &mdash; and **loading** is one of them:

```js
// ...
props: {
    // ...
    loading: {
      type: Boolean,
      description: 'If a form is in loading state, it will automatically show a loading indicator.',
    },
   // ...
},
// ...
```

So, in this case, you don't have to use `state`.
