### ISSUE TITLE
Specify custom icon

### ISSUE THREAD

**Issue by rcffc** [Semantic-UI-Vue/Semantic-UI-Vue#345]
Hey all, 
is there a possibility to specify a custom icon in the [LabeledIcon](https://semantic-ui-vue.github.io/#/elements/button) button?

**Comment by mariolamacchia** [comment]
It's possible but the padding is a bit off. 

`icon` should not only accept a string, but also a boolean.

You can manually add `class="icon"` while we fix it: https://codesandbox.io/s/simple-semantic-ui-vue-example-eqx3z
