### ISSUE TITLE
Add examples for Card

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#35]
ATM the [Accordion page](https://semantic-ui-vue.github.io/#/views/card) is missing examples. Ideally, it should be the same as the [original doc](https://semantic-ui.com/views/card.html). Instructions on how to add examples [here](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md#add-an-example)

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by jaime-lynn** [comment]
I'd be happy to pick this one up
