### ISSUE TITLE
Add examples for Accordion

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#36]
ATM the [Accordion page](https://semantic-ui-vue.github.io/#/modules/accordion) is missing examples. Ideally, it should be the same as the [original doc](https://semantic-ui.com/modules/accordion.html). Instructions on how to add examples [here](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md#add-an-example)

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by agatac** [comment]
I can help with this one
