### ISSUE TITLE
Add examples for Checkbox

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#37]
We need to have the same examples of the [original doc](https://semantic-ui.com/modules/checkbox.html). Instructions [here](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md#add-an-example)

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by ArunaMaurya221B** [comment]
Could you be a little clear of what do you want.

**Comment by mariolamacchia** [comment]
The docs need some examples for the Checkbox component: https://semantic-ui-vue.github.io/#/modules/checkbox. There are instructions on how to add examples in the links above

**Comment by akmittal** [comment]
I have created a pull request. Please review.

**Comment by mariolamacchia** [comment]
Released in 0.0.24
