### ISSUE TITLE
Add examples for Dropdown

### ISSUE THREAD

**Issue by Iworb** [Semantic-UI-Vue/Semantic-UI-Vue#38]
I'm not sure is it ready, but UMD version doen't work, so maybe example could show the way how to make it works.

**Comment by mariolamacchia** [comment]
@Iworb the UMD version seems to work: here is a basic example of a dropdown https://jsfiddle.net/q5m8ureL/. I'll add examples on the docs asap

**Comment by Iworb** [comment]
What about "select" dropdowns? Or multilselect? I've tried to lookup code and didn't find binding for value, etc.

**Comment by mariolamacchia** [comment]
That is still WIP, any help is more welcome :)
