### ISSUE TITLE
[Comment] Add variations

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#398]
Add the same behaviour as the original component: https://semantic-ui.com/views/comment.html#variations

Comment's variations include: 
- [ ] threaded
- [ ] minimal
- [ ] size

Please have a look at contributing.md for instructions on how to contribute and submit a PR.

**Comment by luizzzdev** [comment]
I'll take this one.

**Comment by luizzzdev** [comment]
I'll let this as WIP untill we fix the build
