### ISSUE TITLE
sui-checkbox component @change event

### ISSUE THREAD

**Issue by berlaga** [Semantic-UI-Vue/Semantic-UI-Vue#430]
Is it possible to return entire event object on change, like with plain checkbox? Look at scenario below
```javascript
<sui-form-field v-for="category in categoryList" v-bind:key="category.id">
 <div class="ui checkbox">
  <input type="checkbox" v-bind:value='category.id' v-model="selected_categories" @change="onCategorySelected">
   <label>{{category.name}}</label>
 </div>                    
</sui-form-field>  
```
onCategorySelected callback in this case will be passed a parameter: event. 
One can check for event.target.checked value (checked / unchecked) and event.target.value for bound value. In scenario above, using sui-checkbox is impossible to know if item is checked or unchecked.

**Comment by Mupati** [comment]
@berlaga  can you share your method?  I think you can have something like this.
```
  methods: {
    onCategorySelected: e => {
      console.log(e.target.value);
    }
  }
```
