### ISSUE TITLE
[Dropdown] The .native modifier for v-on is only valid on components

### ISSUE THREAD

**Issue by stuta** [Semantic-UI-Vue/Semantic-UI-Vue#437]
With latest Vue I get this warning:

```
[component warning] The .native modifier for v-on is only valid on components but it was used on <div>.
found in
---> <SuiDropdown>
```

**Comment by jafri** [comment]
@mariolamacchia this is filling up the console !

**Comment by digi604** [comment]
I have the same issue

**Comment by mariolamacchia** [comment]
Fixed in #443

**Comment by negaodanado** [comment]
I have the same issue =(

**Comment by mariolamacchia** [comment]
Can you link a [Codesandbox](https://codesandbox.io/s/618o6oy16k) that reproduces your problem?

**Comment by negaodanado** [comment]
> Can you link a [Codesandbox](https://codesandbox.io/s/618o6oy16k) that reproduces your problem?

I updated to version "0.10.1" and the error disappeared, thanks for your attention!
