### ISSUE TITLE
Bug report: Dropdown with multiple selection + search option

### ISSUE THREAD

**Issue by mdebortoli** [Semantic-UI-Vue/Semantic-UI-Vue#454]
* **I'm submitting a ...**
  - [x] bug report

* **Do you want to request a *feature* or report a *bug*?**
Report a bug on the dropdown component while using multiple selection + search option.

* **What is the current behavior?**
I found this bug while using the feature myself, and after investigating, found the same issue even when trying it on the official Semantic-UI Vue examples on CodeSandbox.
**Bug description:** If you type anything in the search field and select the item, the selected item will not be the correct one.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
**Official documented feature sample:** [https://codesandbox.io/s/qsr8h?module=/Example.vue](https://codesandbox.io/s/qsr8h?module=/Example.vue)
**Bug example:** [https://share.getcloudapp.com/o0uDEQnL](https://share.getcloudapp.com/o0uDEQnL)

**Comment by harrisnl** [comment]
This bug is still present in current version, can this pull request please be merged?

**Comment by harrisnl** [comment]
There is another issue related to this bug:

When using multiple selection with search, the search query is also set as a selected dropdown value. The model then has a selected value that is not in the options attribute.
