### ISSUE TITLE
Sidebar close on click outside

### ISSUE THREAD

**Issue by janat08** [Semantic-UI-Vue/Semantic-UI-Vue#5]
I don't even know what option this is, but in examples https://semantic-ui.com/modules/sidebar.html#/definition sidebar will close after open upon clicking outside the sidebar.

**Comment by mariolamacchia** [comment]
I think the best way to achieve that is by adding an onClick event on the SuiSidebarPusher component. You can see it [on the mobile version of the docs](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/docs/Docs.vue#L23-L27).
