### ISSUE TITLE
Modal dialog & other sizes (existing in official SUI CSS)

### ISSUE THREAD

**Issue by czbaker** [Semantic-UI-Vue/Semantic-UI-Vue#6]
So, it turns out that the "tiny" size for the Modal component was left out of the prop validation, and possibly others (It looks like only fullscreen/small/medium/large are accounted for).

Is there any specific reason the other possible classes/settings for Modal size were omitted in the validation?  I checked the vanilla SUI docs and they mention several others (mini/tiny are the ones that I see right offhand).

I'd like to see those accounted for in the validation (they work (as they do exist in SUI's CSS), but produce warnings/errors in console when used).

I added them and submitted a PR.   First time doing that on GitHub, guess there's a first time for everything, huh?

#7

**Comment by mariolamacchia** [comment]
No specific reason, they were just omitted by mistake. Thanks for reporting.

**Comment by mariolamacchia** [comment]
Fixed in 0.0.17
