### ISSUE TITLE
Create login layout

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#61]
We need a login layout like the in official docs: https://semantic-ui.com/examples/login.html

**Comment by cwhitby** [comment]
Hey, OK if I have a crack at this one?

**Comment by mariolamacchia** [comment]
Sure! Feel free to ask any help if you need it

**Comment by mariolamacchia** [comment]
Sure! Feel free to ask any help if you need it

**Comment by mariolamacchia** [comment]
Sure! Feel free to ask any help if you need it

**Comment by ArStah** [comment]
This issue supposed to be closed, isn't it?

**Comment by mariolamacchia** [comment]
Yep
