### ISSUE TITLE
How to change default tag

### ISSUE THREAD

**Issue by blindsamson** [Semantic-UI-Vue/Semantic-UI-Vue#68]
I'm trying to change the default tag on a menu item from <div> to <a>. I was able to find a reference to change the tag in getElementType.js but it appears there's a piece missing or that I am missing something. 

This line: 
`const tag = instance.$vnode && instance.$vnode.data.tag;`

I think should be like this:
`const tag = instance.$vnode && instance.$vnode.data.attrs.tag;`

Am I correct, or would you be able to tell me how?

**Comment by mariolamacchia** [comment]
Yes, actually the default tag for the menu item should be `<a>`. 

Each component uses `getElementType` to define which tag to use (it allows you to use a different tag). The second argument of `getElementType` is the default tag (`div` by default).

It should be enough to add `a` as second argument [here](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/src/collections/Menu/MenuItem.jsx#L18)

**Comment by blindsamson** [comment]
Thanks for the clarification, but I was wondering if there was also a way to override the default tag dynamically? Something like:

`<sui-menu-item tag="span">Home</sui-menu-item>`

**Comment by mariolamacchia** [comment]
Yep: `<span is="sui-menu-item">Home</span>`

**Comment by mariolamacchia** [comment]
I'll close this one. Please let me know if there are any problems :relaxed:
