### ISSUE TITLE
Problem of the document website.

### ISSUE THREAD

**Issue by ObservedObserver** [Semantic-UI-Vue/Semantic-UI-Vue#79]
I tried to visit [https://semantic-ui-vue.github.io](https://semantic-ui-vue.github.io).
However, no matter which link I click, it goes to the getting started page.
I found there is a `#` in the url, like:
```
https://semantic-ui-vue.github.io/#/elements/list
```
Maybe it didn't turn the history mode on...

**Comment by mariolamacchia** [comment]
Fixed by #80. Link to #81
