### ISSUE TITLE
Create Feed component

### ISSUE THREAD

**Issue by mariolamacchia** [Semantic-UI-Vue/Semantic-UI-Vue#8]
Here is the original one: https://semantic-ui.com/views/feed.html.

Please have a look at [contributing.md](https://github.com/Semantic-UI-Vue/Semantic-UI-Vue/blob/master/CONTRIBUTING.md) for instructions on how to contribute and submit a PR.

**Comment by viettrung9012** [comment]
Let me take a stab on this

**Comment by viettrung9012** [comment]
@mariolamacchia PR is updated and ready for review
