### ISSUE TITLE
Install breaks a brand new `vue init webpack-simple` project

### ISSUE THREAD

**Issue by jarrettv** [Semantic-UI-Vue/Semantic-UI-Vue#89]
Create a brand new project with vuecli and then node install this project and it breaks the project.

[Vue warn]: Failed to mount component: template or render function not defined.

found in

---> <Anonymous>
       <Root>
warn @ webpack-internal:///1:579

**Comment by mariolamacchia** [comment]
What did you change in the project?

**Comment by jarrettv** [comment]
Nothing, here are the commands to reproduce:
`vue init webpack-simple suivue-test`
`cd suivue-test`
`npm install`
`npm run dev`

Verify it works fine, then

`npm install semantic-ui-vue --save`

Now it is broken.

**Comment by mariolamacchia** [comment]
If you are not even importing semantic-ui-vue in your code it must be something wrong with something else. What do you mean with "broken" after which command do you get that error?

**Comment by ArStah** [comment]
Agree with Mario, i just tried to do your steps, added this:
```js
import suiVue from "semantic-ui-vue";
Vue.use(suiVue);
```
to `src/main.js` and it works

**Comment by jarrettv** [comment]
I'm new with both webpack and vue so it is probably my fault. Let me dig deeper. Thanks!

**Comment by mariolamacchia** [comment]
@jarrettv Did you figure this out? Can I close the issue?

**Comment by ArStah** [comment]
Closing, feel free to reopen if necessary
